source "https://rubygems.org"

gem "active_youtube", "1.0.0"
gem "fastercsv", "1.5.0"
gem "ferret", "0.11.6"
gem "flickr_fu", "0.3.0"
gem "hpricot", "0.8.2"
gem "mime-types", "1.16"
gem "nokogiri", "1.5.10"
gem "pg"
gem "rdoc"
gem "rdoc-data"
