source "https://rubygems.org"

gem "dynamic_form"
gem "erubis"
gem "fastercsv", "1.5.0"
gem "ferret"
gem "flickr_fu", "0.3.0"
gem "haml"
gem "hpricot", "0.8.2"
gem "mime-types", "1.16"
gem "nokogiri", "1.5.10"
gem "paperclip", "~> 2.7"
gem "pg"
gem "rails", "3.0.20"
gem "rdoc"
gem "rspec"
