Alacarte::Application.routes.draw do
  root :to => 'login#login'
  get ':controller/service.wsdl' => '#wsdl'
  get 'course-guides/' => 'ica#published_pages'
  get 'course-guides/archived/' => 'ica#archived'
  get 'course-guides/tagged/:id' => 'ica#tagged'
  get 'course-guide/:id' => 'ica#index'
  get 'subject-guides/' => 'srg#published_guides'
  get 'subject-guides/tagged/:id' => 'srg#tagged'
  get 'subject-guide/:id' => 'srg#index'
  get 'guides/search/' => 'srg#search'
  get 'internal-guides/' => 'srg#internal_guides'
  get 'tutorials' => 'ort#published_tutorials'
  get 'tutorials/archived/' => 'ort#archived_tutorials'
  get 'tutorials/:id' => 'ort#index'
  get 'tutorials/unit/:id' => 'ort#unit'
  get 'tutorials/lesson/:id' => 'ort#lesson'
  get 'tutorials/tagged/:id' => 'ort#tagged'
  get 'tutorials/subject/:id' => 'ort#subject_list'
  get 'tutorials/my-quizzes/:id' => 'student#quizzes'
  get 'tutorials/login/:id' => 'student#login'
  get 'tutorials/create-account/:id' => 'student#create_account'
  get '/javascripts/tiny_mce/plugins/advimage_uploader/image.htm' => 'image_manager#create', :via => :post
  get '/javascripts/tiny_mce/plugins/advimage_uploader/image.htm' => 'image_manager#show', :via => :get
  match '/:controller(/:action(/:id))'
end
