Alacarte::Application.routes.draw do
  match '' => 'login#login'
  match ':controller/service.wsdl' => '#wsdl'
  match 'course-guides/' => 'ica#published_pages'
  match 'course-guides/archived/' => 'ica#archived'
  match 'course-guides/tagged/:id' => 'ica#tagged'
  match 'course-guide/:id' => 'ica#index'
  match 'subject-guides/' => 'srg#published_guides'
  match 'subject-guides/tagged/:id' => 'srg#tagged'
  match 'subject-guide/:id' => 'srg#index'
  match 'guides/search/' => 'srg#search'
  match 'internal-guides/' => 'srg#internal_guides'
  match 'tutorials' => 'ort#published_tutorials'
  match 'tutorials/archived/' => 'ort#archived_tutorials'
  match 'tutorials/:id' => 'ort#index'
  match 'tutorials/unit/:id' => 'ort#unit'
  match 'tutorials/lesson/:id' => 'ort#lesson'
  match 'tutorials/tagged/:id' => 'ort#tagged'
  match 'tutorials/subject/:id' => 'ort#subject_list'
  match 'tutorials/my-quizzes/:id' => 'student#quizzes'
  match 'tutorials/login/:id' => 'student#login'
  match 'tutorials/create-account/:id' => 'student#create_account'
  match '/javascripts/tiny_mce/plugins/advimage_uploader/image.htm' => 'image_manager#create', :via => :post
  match '/javascripts/tiny_mce/plugins/advimage_uploader/image.htm' => 'image_manager#show', :via => :get
  match '/:controller(/:action(/:id))'
end
