menubar:
  - edit
  - view
  - tools
toolbar:
  - styleselect
  - bold
  - italic
  - alignleft
  - aligncenter
  - alignright
  - alignjustify
  - bullist
  - numlist
  - outdent
  - indent
  - link
  - anchor
  - table
  - image
  - code
plugins:
  - hr
  - anchor
  - link
  - image
  - fullscreen
  - code
  - spellchecker
  - preview
  - table
height: 500
