theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add:
  - forecolor
  - bold
  - italic
  - underline
  - link
  - unlink
  - anchor
  - image
  - bullist
  - numlist
  - blockquote
  - hr
  - separator
  - outdent
  - indent
  - pasteword
  - removeformat
  - code
  - undo
  - redo
  - fullscreen
  - preview
  - charmap
  - spellchecker
plugins:
  - advlink
  - fullscreen
  - media
  - preview
  - paste
  - spellchecker
  - table
  - fullscreen
content_css: "/stylesheets/tool.css"
fix_list_elements: true
height: 50
