#!/usr/bin/env ruby
require File.expand_path('../../config/environment', __FILE__)

#Create the default admin user
user = User.new :name => "Admin",
                :password => "adm!n",
                :password_confirmation => "adm!n",
                :email => "admin@your-domain.com",
                :role => "admin"
user.role = "admin" #attr_protected is set, so assigning indirectly
user.save

#Create the localization 
local = Local.new 
local.save


puts "Created default administrator.\n  Username: #{user.email}\n  Password: adm!n\nPlease change the password and email address immediately!\n"
